using System;
using System.Collections.Generic;
using System.Text;

// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.EM.Food.Cafe
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.EM.Framework.Resolvers;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Cheese")]
    [Weight(300)]
    [Ecopedia("Food", "Ingredients", createAsSubPage: true)]
    public partial class CheeseItem : FoodItem, IConfigurableFoodItem
    {
        public override LocString DisplayNamePlural => Localizer.DoStr("Cheese");
        public override LocString DisplayDescription => Localizer.DoStr("Milk... at somepoint in time.");
        private static readonly FoodItemModel defaults = new(typeof(CheeseItem), "Cheese", calories: 400, carbs: 1.3f, fat: 5.3f, protein: 20.5f, shelflife: 72, vitamins: 2);

        public override float Calories => EMFoodItemResolver.Obj.ResolveCalories(this);
        public override Nutrients Nutrition => EMFoodItemResolver.Obj.ResolveNutrients(this);
        protected override float BaseShelfLife => EMFoodItemResolver.Obj.ResolveShelfLife(this);
        static CheeseItem() => EMFoodItemResolver.AddDefaults(defaults);
    }

    [RequiresSkill(typeof(CookingSkill), 1)]
    public partial class CheeseRecipe : RecipeFamily, IConfigurableRecipe
    {
        static RecipeDefaultModel Defaults => new()
        {
            ModelType = typeof(CheeseRecipe).Name,
            Assembly = typeof(CheeseRecipe).AssemblyQualifiedName,
            HiddenName = "Cheese",
            LocalizableName = Localizer.DoStr("Cheese"),
            IngredientList = new()
            {
                new EMIngredient("Milk", true, 3, true),
            },
            ProductList = new()
            {
                new EMCraftable("CheeseItem")
            },
            BaseExperienceOnCraft = 1,
            BaseLabor = 25,
            LaborIsStatic = false,
            BaseCraftTime = 1,
            CraftTimeIsStatic = false,
            CraftingStation = "StoveItem",
            RequiredSkillType = typeof(CookingSkill),
            RequiredSkillLevel = 1
        };

        static CheeseRecipe() { EMRecipeResolver.AddDefaults(Defaults); }

        public CheeseRecipe()
        {
            this.Recipes = EMRecipeResolver.Obj.ResolveRecipe(this);
            this.LaborInCalories = EMRecipeResolver.Obj.ResolveLabor(this);
            this.CraftMinutes = EMRecipeResolver.Obj.ResolveCraftMinutes(this);
            this.ExperienceOnCraft = EMRecipeResolver.Obj.ResolveExperience(this);
            this.Initialize(Defaults.LocalizableName, GetType());
            CraftingComponent.AddRecipe(EMRecipeResolver.Obj.ResolveStation(this), this);
        }
    }
}
