using System;
using System.Collections.Generic;
using System.Text;

// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.EM.Food.Cuisine
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Chicken Noodle Soup")]
    [Weight(300)]
    //[Tag("BakedVegetable", 1)]
    //[Tag("BakedFood", 1)]
    [Ecopedia("Food", "Baking", createAsSubPage: true)]
    public partial class ChickenNoodleSoupFoodItem : FoodItem
    {
        public override LocString DisplayNamePlural => Localizer.DoStr("Chicken Noodle Soup");
        public override LocString DisplayDescription => Localizer.DoStr("Noodle in chicken broth.");

        public override float Calories => 700;
        public override Nutrients Nutrition => new Nutrients() { Carbs = 50, Fat = 5, Protein = 15, Vitamins = 0 };

        protected override int BaseShelfLife => throw new NotImplementedException();
    }

    [RequiresSkill(typeof(CookingSkill), 1)]
    public partial class ChickenNoodleSoupFoodRecipe : RecipeFamily
    {
        public ChickenNoodleSoupFoodRecipe()
        {
            var product = new Recipe(
                "Chicken Noodle Soup",
                Localizer.DoStr("Chicken Noodle Soup"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(NoodleFoodItem), 1, typeof(CookingSkill)),
                    new IngredientElement(typeof(MeatStockItem), 1, typeof(CookingSkill)),
                },
                new CraftingElement<ChickenNoodleSoupFoodItem>(1)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(30, typeof(CookingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(ChickenNoodleSoupFoodRecipe), 1, typeof(CookingSkill), typeof(CookingFocusedSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Chicken Noodle Soup"), typeof(ChickenNoodleSoupFoodRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(StoveObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
