using System;
using System.Collections.Generic;
using System.Text;

// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.EM.Food.Cafe
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Tomato Sauce")]
    [Weight(300)]
    //[Tag("BakedVegetable", 1)]
    //[Tag("BakedFood", 1)]
    [Ecopedia("Food", "Baking", createAsSubPage: true)]
    public partial class TomatoSauceFoodItem : FoodItem
    {
        public override LocString DisplayNamePlural => Localizer.DoStr("Also known as ketchup.");
        public override LocString DisplayDescription => Localizer.DoStr("Egg boiled in water.");

        public override float Calories => 30;
        public override Nutrients Nutrition => new Nutrients() { Carbs = 4f, Fat = 0, Protein = 1, Vitamins = 0 };

        protected override int BaseShelfLife => throw new NotImplementedException();
    }

    [RequiresSkill(typeof(CookingSkill), 1)]
    public partial class TomatoSauceFoodRecipe : RecipeFamily
    {
        public TomatoSauceFoodRecipe()
        {
            var product = new Recipe(
                "Tomato Sauce",
                Localizer.DoStr("Tomato Sauce"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(TomatoItem), 1, typeof(CookingSkill)),
                    new IngredientElement(typeof(SugarItem), 1, typeof(CookingSkill)),
                },
                new CraftingElement<TomatoSauceFoodItem>(6)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(15, typeof(CookingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(TomatoSauceFoodRecipe), 1, typeof(CookingSkill), typeof(CookingFocusedSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Tomato Sauce"), typeof(TomatoSauceFoodRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(KitchenObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
