using System;
using System.Collections.Generic;
using System.Text;

// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.EM.Food.Cuisine
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Spaghetti Bolognese")]
    [Weight(300)]
    //[Tag("BakedVegetable", 1)]
    //[Tag("BakedFood", 1)]
    [Ecopedia("Food", "Baking", createAsSubPage: true)]
    public partial class SpaghettiBologneseFoodItem : FoodItem
    {
        public override LocString DisplayNamePlural => Localizer.DoStr("Spaghetti Bolognese");
        public override LocString DisplayDescription => Localizer.DoStr("Pasta in tomato sauce.");

        public override float Calories => 400;
        public override Nutrients Nutrition => new Nutrients() { Carbs = 50, Fat = 3, Protein = 25, Vitamins = 0};

        protected override float BaseShelfLife => throw new NotImplementedException();
    }

    [RequiresSkill(typeof(CookingSkill), 1)]
    public partial class SpaghettiBologneseFoodRecipe : RecipeFamily
    {
        public SpaghettiBologneseFoodRecipe()
        {
            var product = new Recipe(
                "Spaghetti Bolognese",
                Localizer.DoStr("Spaghetti Bolognese"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(NoodleFoodItem), 1, typeof(CookingSkill)),
                    new IngredientElement(typeof(RawMeatItem), 1, typeof(CookingSkill)),
                },
                new CraftingElement<SpaghettiBologneseFoodItem>(1)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(30, typeof(CookingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(SpaghettiBologneseFoodRecipe), 1, typeof(CookingSkill), typeof(CookingFocusedSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Spaghetti Bolognese"), typeof(SpaghettiBologneseFoodRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(StoveObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
