using System;
using System.Collections.Generic;
using System.Text;

// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.PlanetChefMod
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Huckleberry Wine")]
    [Weight(300)]
    //[Tag("BakedVegetable", 1)]
    //[Tag("BakedFood", 1)]
    [Ecopedia("Food", "Baking", createAsSubPage: true)]
    public partial class HuckleberryWineFoodItem : FoodItem
    {
        public override LocString DisplayNamePlural => Localizer.DoStr("Huckleberry Wine");
        public override LocString DisplayDescription => Localizer.DoStr("12% alcohol.");

        public override float Calories => 45;
        public override Nutrients Nutrition => new Nutrients() { Carbs = 0f, Fat = 0, Protein = 0, Vitamins = 0 };

        protected override float BaseShelfLife => throw new NotImplementedException();
    }

    [RequiresSkill(typeof(CookingSkill), 1)]
    public partial class HuckleberryWineFoodRecipe : RecipeFamily
    {
        public HuckleberryWineFoodRecipe()
        {
            var product = new Recipe(
                "Huckleberry Wine",
                Localizer.DoStr("Huckleberry Wine"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(HuckleberryExtractItem), 10, typeof(CookingSkill)),
                },
                new CraftingElement<HuckleberryWineFoodItem>(1)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(25, typeof(CookingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(HuckleberryWineFoodRecipe), 1, typeof(CookingSkill), typeof(CookingFocusedSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Huckleberry Wine"), typeof(HuckleberryWineFoodRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(AgingBarrelObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
