using System;
using System.Collections.Generic;
using System.Text;

// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.EM.Food.Cuisine
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Egg Caserole")]
    [Weight(300)]
    //[Tag("BakedVegetable", 1)]
    //[Tag("BakedFood", 1)]
    [Ecopedia("Food", "Baking", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]
    public partial class EggCaseroleFoodItem : FoodItem
    {
        public override LocString DisplayNamePlural => Localizer.DoStr("Egg Caserole");
        public override LocString DisplayDescription => Localizer.DoStr("Egg baked with vegetables.");

        public override float Calories => 500;
        public override Nutrients Nutrition => new Nutrients() { Carbs = 5f, Fat = 4, Protein = 5.0f, Vitamins = 3 };
    }

    [RequiresSkill(typeof(CookingSkill), 1)]
    public partial class EggCaseroleFoodRecipe : RecipeFamily
    {
        public EggCaseroleFoodRecipe()
        {
            var product = new Recipe(
                "Egg Caserole",
                Localizer.DoStr("Egg Caserole"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(VegetableMedleyItem), 1, typeof(CookingSkill)),
                },
                new CraftingElement<EggCaseroleFoodItem>(1)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(35, typeof(CookingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(EggCaseroleFoodRecipe), 1, typeof(CookingSkill), typeof(CookingFocusedSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Egg Caserole"), typeof(EggCaseroleFoodRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(BakeryOvenObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
