using System;
using System.Collections.Generic;
using System.Text;

// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.EM.Food.Cuisine
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Seafood Stock")]
    [Weight(300)]
    //[Tag("BakedVegetable", 1)]
    //[Tag("BakedFood", 1)]
    [Ecopedia("Food", "Baking", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]
    public partial class SeafoodStockFoodItem : FoodItem
    {
        public override LocString DisplayNamePlural => Localizer.DoStr("Seafood Stock");
        public override LocString DisplayDescription => Localizer.DoStr("Essence of the sea.");

        public override float Calories => 17;
        public override Nutrients Nutrition => new Nutrients() { Carbs = 0f, Fat = 0.8f, Protein = 2.3f, Vitamins = 2 };
    }

    [RequiresSkill(typeof(CookingSkill), 1)]
    public partial class SeafoodStockFoodRecipe : RecipeFamily
    {
        public SeafoodStockFoodRecipe()
        {
            var product = new Recipe(
                "Seafood Stock",
                Localizer.DoStr("Seafood Stock"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(RawFishItem), 4, typeof(CookingSkill)),
                    new IngredientElement(typeof(KelpItem), 2, typeof(CookingSkill)),
                },
                new CraftingElement<SeafoodStockFoodItem>(1)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(25, typeof(CookingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(SeafoodStockFoodRecipe), 1, typeof(CookingSkill), typeof(CookingFocusedSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Seafood Stock"), typeof(SeafoodStockFoodRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(CastIronStoveObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
