using System;
using System.Collections.Generic;
using System.Text;

// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.EM.Food.Cuisine
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Sushi")]
    [Weight(300)]
    //[Tag("BakedVegetable", 1)]
    //[Tag("BakedFood", 1)]
    [Ecopedia("Food", "Baking", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]
    public partial class SushiFoodItem : FoodItem
    {
        public override LocString DisplayNamePlural => Localizer.DoStr("Sushi");
        public override LocString DisplayDescription => Localizer.DoStr("Staple food of an island country.");

        public override float Calories => 120;
        public override Nutrients Nutrition => new Nutrients() { Carbs = 2.1f, Fat = 1, Protein = 2.5f, Vitamins = 1 };
    }

    [RequiresSkill(typeof(CookingSkill), 1)]
    public partial class SushiFoodRecipe : RecipeFamily
    {
        public SushiFoodRecipe()
        {
            var product = new Recipe(
                "Sushi",
                Localizer.DoStr("Sushi"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(RawFishItem), 1, typeof(CookingSkill)),
                    new IngredientElement(typeof(KelpItem), 1, typeof(CookingSkill)),
                    new IngredientElement(typeof(BoiledRiceItem), 1, typeof(CookingSkill)),
                },
                new CraftingElement<SushiFoodItem>(6)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(90, typeof(CookingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(SushiFoodRecipe), 1, typeof(CookingSkill), typeof(CookingFocusedSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Sushi"), typeof(SushiFoodRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(KitchenObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
