using System;
using System.Collections.Generic;
using System.Text;

// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.EM.Food.Cafe
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.EM.Framework.Resolvers;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Pineapple Juice")]
    [Weight(300)]
    [Ecopedia("Food", "Cooking", createAsSubPage: true)]
    public partial class PineappleJuiceItem : FoodItem, IConfigurableFoodItem
    {
        public override LocString DisplayNamePlural => Localizer.DoStr("Pineapple Juice");
        public override LocString DisplayDescription => Localizer.DoStr("A Refreshing Burst of vitamins.");
        private static readonly FoodItemModel defaults = new(typeof(PineappleJuiceItem), "Mayonaise", calories: 100, carbs: 0, fat: 0, protein: 0, vitamins: 10, shelflife: 72);

        protected override float BaseShelfLife => EMFoodItemResolver.Obj.ResolveShelfLife(this);
        public override float Calories => EMFoodItemResolver.Obj.ResolveCalories(this);
        public override Nutrients Nutrition => EMFoodItemResolver.Obj.ResolveNutrients(this);
        static PineappleJuiceItem() => EMFoodItemResolver.AddDefaults(defaults);
    }

    [RequiresSkill(typeof(CookingSkill), 1)]
    public partial class PineappleJuiceRecipe : RecipeFamily, IConfigurableRecipe
    {
        static RecipeDefaultModel Defaults => new()
        {
            ModelType = typeof(PineappleJuiceRecipe).Name,
            Assembly = typeof(PineappleJuiceRecipe).AssemblyQualifiedName,
            HiddenName = "Pineapple Juice",
            LocalizableName = Localizer.DoStr("Pineapple Juice"),
            IngredientList = new()
            {
                new EMIngredient("PineappleItem", false, 10),
            },
            ProductList = new()
            {
                new EMCraftable("PineappleJuiceItem", 4),
            },
            BaseExperienceOnCraft = 1,
            BaseLabor = 50,
            LaborIsStatic = false,
            BaseCraftTime = 0.5f,
            CraftTimeIsStatic = false,
            CraftingStation = "BlenderItem",
            RequiredSkillType = typeof(CookingSkill),
            RequiredSkillLevel = 1,
            IngredientImprovementTalents = typeof(CookingLavishResourcesTalent),
            SpeedImprovementTalents = new Type[] { typeof(CookingFocusedSpeedTalent), typeof(CookingParallelSpeedTalent) },
        };

        static PineappleJuiceRecipe() { EMRecipeResolver.AddDefaults(Defaults); }

        public PineappleJuiceRecipe()
        {
            this.Recipes = EMRecipeResolver.Obj.ResolveRecipe(this);
            this.LaborInCalories = EMRecipeResolver.Obj.ResolveLabor(this);
            this.CraftMinutes = EMRecipeResolver.Obj.ResolveCraftMinutes(this);
            this.ExperienceOnCraft = EMRecipeResolver.Obj.ResolveExperience(this);
            this.Initialize(EMRecipeResolver.Obj.ResolveRecipeName(this), GetType());
            CraftingComponent.AddRecipe(EMRecipeResolver.Obj.ResolveStation(this), this);
        }
    }
}
